---
logging:
  level:
    org.keycloak.admin.client: DEBUG
    org.friesoft.porturl: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8443/realms/porturl-local
porturl:
  security:
    validate-issuer: false
  cleanup:
    enabled: true
    cron: "0 * * * * *"
  otel:
    enabled: false
  storage:
    type: YAML
    #type: SQL
  keycloak:
    realm: porturl-local
    truststore-path: local-dev/tls/truststore.jks
    truststore-password: changeit
    admin:
      server-url: https://localhost:8443
      realm: porturl-local
      client-id: porturl-management-client
      client-secret: local-management-secret
    cross-realm:
      server-url: https://localhost:8443
      realm: master
      client-id: porturl-cross-realm-client
      client-secret: master-management-secret
springdoc:
  swagger-ui:
    oauth:
      client-id: porturl-backend-swagger-client
      use-pkce-with-authorization-code-grant: true
management:
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    sampling:
       probability: 1.0
